Update sync_to_gitee.yml token ckeck

diff --git a/.github/workflows/syns_to_gitee.yml b/.github/workflows/syns_to_gitee.yml
--- a/.github/workflows/syns_to_gitee.yml
+++ b/.github/workflows/syns_to_gitee.yml
@@ -12,8 +12,15 @@ jobs:
         with:
               ref: main
               fetch-depth: 0
-      - name: Debug GITEE_TOKEN
-        run: echo "TOKEN_LENGTH=${#GITEE_TOKEN}"   
+      - name: Check GITEE_TOKEN
+        env:
+          GITEE_TOKEN: ${{ secrets.GITEE_TOKEN }}
+        run: |
+          if [ -z "$GITEE_TOKEN" ]; then
+            echo "Error: GITEE_TOKEN is empty!"
+            exit 1
+          fi
+            echo "GITEE_TOKEN is set correctly."
             
       - name: Get REPO_NAME
         run: echo "REPO_NAME=$(echo ${{ github.repository }} | cut -d'/' -f2)" >> $GITHUB_ENV
@@ -25,5 +32,5 @@ jobs:
         
       - name: Mirror to Gitee        
         run: |              
-            git remote add gitee https://${{ github.repository_owner }}:${{ secrets.GITEE_TOKEN }}@gitee.com/${{ github.repository_owner }}/${{ env.REPO_NAME }}.git 
+            git remote add gitee https://yangdavid988:${{ secrets.GITEE_TOKEN }}@gitee.com/${{ github.repository_owner }}/${{ env.REPO_NAME }}.git 
             git push gitee HEAD:refs/heads/main --force
